Fix 'pragma solidity' parsing
ConsenSysDiligence/mythril pull request #1887
Opened 2024-10-30 09:23 UTC by gsalzer

remove comments and strings before searching for a line containing 'pragma solidity'

2024-10-30 09:29 UTC, gsalzer commented
The patch tries to be minimally invasive; you may want to integrate it better. The comment citing the source can be removed (no need to give credits), it is just to inspire trust (?) that the code works since we used it for processing 100,000+ source codes in one of our studies.

2024-11-05 22:25 UTC, norhh commented
For some reason, I’ve lost access to the CircleCI pipeline results over the past month. @psantos-consensys, could you look into the cause of CircleCI’s failure? Additionally, could you change the permissions to view Mythril’s CircleCI results? Since Mythril is open-source, these results should ideally be public as they were previously.

2024-12-17 15:43 UTC, gsalzer commented
@norhh @psantos-consensys Any chance that something is going to happen in the near future? I'm fine with the pull request being rejected but this CircleCI pipeline issue occurring with every pull request now seems to be unhealthy.

2024-12-17 20:02 UTC, norhh commented
I don't know when it will be fixed/visible. I've asked someone to look into it.

2025-01-06 09:51 UTC, psantos-consensys commented
@norhh can you please double check if it is working as expected now?

2025-01-06 19:57 UTC, norhh commented
@gsalzer, the test failures seem to be due to the test case related to these files: [version_2.sol](https://github.com/Consensys/mythril/blob/develop/tests/testdata/input_contracts/version_2.sol
), [version_3.sol](https://github.com/Consensys/mythril/blob/develop/tests/testdata/input_contracts/version_3.sol).
The comments should be removed from these files.

2025-01-07 18:07 UTC, gsalzer commented
> @gsalzer, the test failures seem to be due to the test case related to these files: [version_2.sol](https://github.com/Consensys/mythril/blob/develop/tests/testdata/input_contracts/version_2.sol), [version_3.sol](https://github.com/Consensys/mythril/blob/develop/tests/testdata/input_contracts/version_3.sol). The comments should be removed from these files.

@norhh Please check the updated code. Now, it first searches for a regular pragma that does not occur in a comment or string, and if this fails, falls back to how Mythril searches the pragma currently (i.e., searching within comments as well).

2025-01-07 19:37 UTC, gsalzer commented
What is the proper way to execute the tests in the `tests` folder?

2025-01-08 11:51 UTC, norhh requested changes
Thanks a lot for the PR. Can you make these quick refactoring changes?

2025-01-08 11:51 UTC, norhh commented on mythril/ethereum/util.py
> +import re
Can you move the import to the top of the file?

2025-01-08 11:51 UTC, norhh commented on mythril/ethereum/util.py
> +    # normalize line endings
This part of extracting the version_line can now be moved to separate function. It'll be easier to read and understand.

2025-01-08 11:51 UTC, norhh commented on mythril/ethereum/util.py
> +def remove_comments_strings(todo):
Can you improve the names for this function? (namely: todo, done, m, m2)

2025-01-08 11:51 UTC, norhh commented on mythril/ethereum/util.py
> +# Return str without Solidity comments and strings
This can be moved to the function def.

2025-01-08 15:52 UTC, gsalzer commented
@norhh Refactoring done.

2025-01-10 02:20 UTC, norhh approved these changes
Thanks for the contribution!

2025-01-10 12:25 UTC, psantos-consensys commented on mythril/ethereum/util.py
> +def remove_comments_strings(program):
thanks all, just a minor thing before merging and I will leave it to @norhh to decide, should we add annotations to the new methods definitions (remove_comments_strings, extract_version_line) for the argument and return types similar to:
`def extract_binary(file: str) -> Tuple[str, str]:`
`def extract_version(program: typing.Optional[str]):`

2025-01-10 12:43 UTC, gsalzer commented on mythril/ethereum/util.py
> +def remove_comments_strings(program):
I have added type annotations to the functions that I have touched.

2025-01-10 12:45 UTC, gsalzer commented on mythril/ethereum/util.py
> +def remove_comments_strings(program):
Doing it is probably faster than discussing it ...

2025-01-10 13:49 UTC, psantos-consensys approved these changes

2025-01-10 13:51 UTC, merged